FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl libc6-compat
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate

ENV NODE_ENV=production
EXPOSE 8080

CMD ["npx", "tsx", "src/jobs/worker.ts"]
